#!/bin/sh

day="$(printf '%02d' ${1##0})"
part=$2
inputfile="$PWD/input/${day}.txt"

./prepare "$day" "$part"

hyperfine -n "$dir" "./run '$day' '$part' '$inputfile'"

./clean "$day" "$part" "$inputfile"